server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/Beaconfire-Jul-2025/Config.git}
          default-label: main
          search-paths: /
          clone-on-start: true
