server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Beaconfire-Jul-2025/Config.git
          default-label: main
          search-paths: /
          clone-on-start: true
